### PR TITLE
Add more controls

### PR DESCRIPTION
**Pull request by Munksgaard**
Add support for vertical scrolling and vertical cursor movement.

I'd like this functionality for https://github.com/Munksgaard/inquirer-rs

### CODE REVIEW

**Comment by Munksgaard** [comment]
Hm, perhaps the documentation for the scrolling functions could be a bit better. I'll update them tonight.

**Comment by ticki** [comment]
Looks good!

**Comment by ticki** [comment]
Somehow forgot to merge... Sorry.

**Comment by Munksgaard** [comment]
Haha, no worries :smile: Thanks for the merge!

**Pull request merged**
