### PR TITLE
Add explicit lifetime parameters to reader iterator trait, allows use of &mut instead of move

### PR DESCRIPTION
**Pull request by mhintz**
So that the input reader iterators can be used in places where a move is not possible and where constantly reinstantiating is not feasible. This change was prompted by needing to work with keyboard input inside of a main loop of a program, without being able to use the normal (synchronous) loop because it blocks. I had tried calling async_stdin() on every loop iteration, but in addition to being probably quite expensive, that function panics every now and again because sometimes stdin isn't available, and an Error is unwrapped in get_tty(). I don't think this changes the external-facing API at all, simply allows a slightly looser use of the main stream because &mut is more flexible than a move.

### CODE REVIEW

**Comment by ticki** [comment]
This makes sense, but it's a breaking change, so it'll need some discussion.

**Comment by ticki** [comment]
@IGI-111 @gyscos 

thoughts?

**Comment by gyscos** [comment]
The actual impact on users depends on how often these iterators are stored (I don't think any example does that).
It still means some (already owned) `Read` may have to be set to `mut`, but this should be a smaller change (though it *will* probably affect many users).

**Comment by gyscos** [comment]
But is it really necessary?
We have:
```
impl<'a, R: Read + ?Sized> Read for &'a mut R
impl<R: Read> TermRead for R
```

So `TermRead` should already be implemented for mutable references to `Read` types.

**Comment by mhintz** [comment]
For the app I built, I was using `stdin.keys()` inside a main loop which did some other calculation. The fact that `.keys()` moves the stdin value meant that the main loop couldn't run, since stdin was being used up on the first iteration.

If I'm understanding you correctly, I suppose I could have stored `mut stdin` and then done something like `(&mut stdin).keys()` to access the keys iterator inside the main loop?

**Comment by gyscos** [comment]
Indeed, `(&mut stdin).keys()` should do the trick. You'd need a `mut stdin` anyway, since in this PR `keys()` takes a `&mut self`.

**Comment by mhintz** [comment]
Seems like kind of an awkward construction but if you don't want to do a breaking change, it's a decent workaround

**Comment by gyscos** [comment]
You can also define `let stdin = &mut stdin;` for the same effect.

Actually, the current method gives more flexibility, as it's possible to "store" the inner `Read` within the iterators. Users can then decide between giving the owned object, or just the mutable reference.

**Comment by IGI-111** [comment]
Gotta admit, I've had similar problems in the past, and I want to err on the side of what gives the most flexibility but I'm not convinced this patch would lead to that.

If I understand correctly, you can absolutely call use an iterator method on an `&mut`, so what's the benefit of forcing references exactly?

Maybe just be clearer in the examples or at least have one that does that (since it doesn't seem evident that you can do it)?

**Pull request closed without merging**
