### PR TITLE
Implemented color for Box<Color> so color can be passed around

### PR DESCRIPTION
**Pull request by AlexanderThaller**
Implemented color for Box<Color> so color can be passed around and doesnt cause problems with sized not being implemented (see issue 123).

### CODE REVIEW

**Comment by TheZalli** [comment]
Wouldn't it be wiser to be more generic and implement Color-trait for all types that implement `Deref<Target=Color>` ?

**Comment by AlexanderThaller** [comment]
I guess so I really just made this change to solve an immediate problem I had. I have to look into how to implement that.

**Comment by TheZalli** [comment]
I'd imagine the trait implementation would start with something like `impl<T> Color for T where T: Deref<Target=Color>`.
After looking at the code that change might be the only thing required really.

**Comment by sashaweiss** [comment]
Hey! Any chance of this being merged in in the near future? I'm running into the same problem, and this looks like a great solution.

**Comment by JoshMcguigan** [comment]
@AlexanderThaller Would you like to add a commit implementing the suggestion by @mrZalli? I'd agree that would be a more general solution.

**Pull request closed without merging**
