### PR TITLE
Add syntax highlightable read line

### PR DESCRIPTION
**Pull request by bjorn3**
Add a syntax highlightable read_line variant.

### CODE REVIEW

**Comment by IGI-111** [comment]
This sounds quite useful, but I wonder if it really belong in TermRead proper. Shouldn't syntax highlightable stuff be a trait onto itself?

Doing writes in TermRead is also a bit weird.

Oh and I'm sure the intention behind it all would be much clearer with a usage example.

**Comment by bjorn3** [comment]
`RawTermRead`?

**Comment by bjorn3** [comment]
Screenshot of example
screenshot of example

**Comment by ticki** [comment]
While nice, I am unsure if it is too high level or not. In fact, I kind of regret adding `read_line` in the first place, because it has proved to be a such a terribly complex thing, and I'd rather not add more in the same style.

Maybe a separate crate? AFAICS there is no dependency on internal components, so it could be done with a crate with `termion` as dependency.

**Comment by ticki** [comment]
Then again, this thing is definitely useful. hmm

**Comment by bjorn3** [comment]
`mod utils`?

**Comment by ticki** [comment]
Oh. A "crate" is a library, not a module.

**Comment by ticki** [comment]
Closing this as out-of-scope. It's certainly cool, but it doesn't fit this library.

**Pull request closed without merging**
