### PR TITLE
Add a HideCursor wrapper type acting like AlternateScreen

### PR DESCRIPTION
**Pull request by mdevlamynck**
This adds a HideCursor type acting just like AlternateScreen, hiding the cursor on construction with from() and showing the cursor on drop().

### CODE REVIEW

**Comment by Mange** [comment]
I'd love to see something like this merged.

**Comment by jackpot51** [comment]
Please submit merge requests here: https://gitlab.redox-os.org/redox-os/termion

**Comment by mdevlamynck** [comment]
https://gitlab.redox-os.org/redox-os/termion/merge_requests/154
Here it is, thanks for pointing this out.

**Comment by jackpot51** [comment]
Thanks

**Pull request closed without merging**
