### PR TITLE
Move system specific features into sys module

### PR DESCRIPTION
**Pull request by jackpot51**
This organizes the system specific code into two modules, redox and unix. Tests are moved when necessary to the root, so they can be run on both modules. Termios is implemented for raw mode on Redox.

### CODE REVIEW

**Comment by jackpot51** [comment]
@ticki Please take a look at this. Redox has made a breaking change so using the new termios methods are the only way of setting up raw mode.

**Comment by jackpot51** [comment]
Thanks!

**Comment by jackpot51** [comment]
@ticki Also need a version bump and cargo publish. Then everything goes back to using upstream termion.

**Comment by ticki** [comment]
should be good now

**Comment by jackpot51** [comment]
:tada:

**Pull request merged**
