### PR TITLE
Refactor read_passwd

### PR DESCRIPTION
**Pull request by untitaker**
Line-reading logic is now in its own method

### CODE REVIEW

**Comment by untitaker** [comment]
@Ticki your opinion?

**Comment by ticki** [comment]
Oh, sorry. I completed missed your PR! Honestly, I don't think I like it, cause from a security stand-point, the application should be able to check if the password is hidden to persons next to the user, since in some cases, it is perfectly fine not to do so, but others it can be quite critical.

So, I will not merge this PR, as is. But you can add another method "try_read_password", which does what you want.

**Comment by untitaker** [comment]
> Honestly, I don't think I like it, cause from a security stand-point, the application should be able to check if the password is hidden to persons next to the user

Perhaps there's a misunderstanding/oversight: This PR doesn't change the behavior of `read_passwd` at all, it just factors out the line-reading loop into its own function.

**Comment by ticki** [comment]
Sorry for inactivity. LFTM.

**Comment by untitaker** [comment]
Excellent, could you release a new version as well? Thanks!

**Comment by ticki** [comment]
@untitaker It isn't on crates.io, you have to use it directly through git:

``` toml
[dependencies.termion]
git = "https://github.com/Ticki/termion.git"
```

**Comment by untitaker** [comment]
Ah yeah, I forgot. Thanks!

**Comment by ticki** [comment]
BTW, I added unit tests. https://github.com/Ticki/termion/commit/6a792cd86d02bf62299cf7ada6b5a8453282467a

**Comment by untitaker** [comment]
Ah, perhaps Travis would've helped for catching those renaming bugs...

**Comment by ticki** [comment]
Oh, that bug was one that was introduced under the merge. Travis wouldn't catch that.

**Pull request merged**
